title: "Jax's Personal Website"
description: "Personal website built with Jekyll."
baseurl: ""
url: "https://yourusername.github.io"

collections:
  posts:
    output: true

# Navigation
nav:
  - name: "About Me"
    url: "/"
  - name: "Projects"
    url: "/projects"
  - name: "Blogs"
    url: "/blogs"

# Markdown and plugins
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages
github:
  is_project_page: true