# Site-wide variables
title: "Jax's Personal Website"
description: "Personal website built with Jekyll."
author: Jax
baseurl: ""
url: "https://kdpkst.github.io"

collections:
  projects:
    output: true   # This tells Jekyll to generate actual HTML files for each project
    permalink: /projects/:title/   # This sets the URL structure for your projects
  posts:
    output: true
    permalink: /blogs/:categories/:year/:month/:day/:title/

# Build settings 
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages
github:
  is_project_page: true

sass:
  sass_dir: _sass
  style: compressed  # or expanded, compact, nested (compressed is good for production)